// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Data;

#nullable disable

namespace TestApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241214174002_addSeed")]
    partial class addSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TestApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Category 1",
                            Name = "Category 1",
                            Slug = "category-1",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Category 2",
                            Name = "Category 2",
                            Slug = "category-2",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Category 3",
                            Name = "Category 3",
                            Slug = "category-3",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Category 4",
                            Name = "Category 4",
                            Slug = "category-4",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Category 5",
                            Name = "Category 5",
                            Slug = "category-5",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for Category 6",
                            Name = "Category 6",
                            Slug = "category-6",
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for Category 7",
                            Name = "Category 7",
                            Slug = "category-7",
                            Status = true
                        });
                });

            modelBuilder.Entity("TestApp.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TestApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Brand 1",
                            CategoryId = 1,
                            Description = "Description for Product 1-1",
                            MetaDescription = "Meta Description for Product 1-1",
                            MetaKeywords = "keyword-1-1",
                            MetaTitle = "Meta Title for Product 1-1",
                            Name = "Product 1-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-1-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Brand 2",
                            CategoryId = 1,
                            Description = "Description for Product 1-2",
                            MetaDescription = "Meta Description for Product 1-2",
                            MetaKeywords = "keyword-1-2",
                            MetaTitle = "Meta Title for Product 1-2",
                            Name = "Product 1-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-1-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Brand 3",
                            CategoryId = 1,
                            Description = "Description for Product 1-3",
                            MetaDescription = "Meta Description for Product 1-3",
                            MetaKeywords = "keyword-1-3",
                            MetaTitle = "Meta Title for Product 1-3",
                            Name = "Product 1-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-1-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Brand 4",
                            CategoryId = 1,
                            Description = "Description for Product 1-4",
                            MetaDescription = "Meta Description for Product 1-4",
                            MetaKeywords = "keyword-1-4",
                            MetaTitle = "Meta Title for Product 1-4",
                            Name = "Product 1-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-1-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Brand 5",
                            CategoryId = 1,
                            Description = "Description for Product 1-5",
                            MetaDescription = "Meta Description for Product 1-5",
                            MetaKeywords = "keyword-1-5",
                            MetaTitle = "Meta Title for Product 1-5",
                            Name = "Product 1-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-1-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Brand 6",
                            CategoryId = 1,
                            Description = "Description for Product 1-6",
                            MetaDescription = "Meta Description for Product 1-6",
                            MetaKeywords = "keyword-1-6",
                            MetaTitle = "Meta Title for Product 1-6",
                            Name = "Product 1-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-1-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Brand 7",
                            CategoryId = 1,
                            Description = "Description for Product 1-7",
                            MetaDescription = "Meta Description for Product 1-7",
                            MetaKeywords = "keyword-1-7",
                            MetaTitle = "Meta Title for Product 1-7",
                            Name = "Product 1-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-1-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Brand 8",
                            CategoryId = 1,
                            Description = "Description for Product 1-8",
                            MetaDescription = "Meta Description for Product 1-8",
                            MetaKeywords = "keyword-1-8",
                            MetaTitle = "Meta Title for Product 1-8",
                            Name = "Product 1-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-1-8",
                            Status = true,
                            Stock = 108
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Brand 1",
                            CategoryId = 2,
                            Description = "Description for Product 2-1",
                            MetaDescription = "Meta Description for Product 2-1",
                            MetaKeywords = "keyword-2-1",
                            MetaTitle = "Meta Title for Product 2-1",
                            Name = "Product 2-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-2-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Brand 2",
                            CategoryId = 2,
                            Description = "Description for Product 2-2",
                            MetaDescription = "Meta Description for Product 2-2",
                            MetaKeywords = "keyword-2-2",
                            MetaTitle = "Meta Title for Product 2-2",
                            Name = "Product 2-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-2-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Brand 3",
                            CategoryId = 2,
                            Description = "Description for Product 2-3",
                            MetaDescription = "Meta Description for Product 2-3",
                            MetaKeywords = "keyword-2-3",
                            MetaTitle = "Meta Title for Product 2-3",
                            Name = "Product 2-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-2-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Brand 4",
                            CategoryId = 2,
                            Description = "Description for Product 2-4",
                            MetaDescription = "Meta Description for Product 2-4",
                            MetaKeywords = "keyword-2-4",
                            MetaTitle = "Meta Title for Product 2-4",
                            Name = "Product 2-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-2-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Brand 5",
                            CategoryId = 2,
                            Description = "Description for Product 2-5",
                            MetaDescription = "Meta Description for Product 2-5",
                            MetaKeywords = "keyword-2-5",
                            MetaTitle = "Meta Title for Product 2-5",
                            Name = "Product 2-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-2-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Brand 6",
                            CategoryId = 2,
                            Description = "Description for Product 2-6",
                            MetaDescription = "Meta Description for Product 2-6",
                            MetaKeywords = "keyword-2-6",
                            MetaTitle = "Meta Title for Product 2-6",
                            Name = "Product 2-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-2-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Brand 7",
                            CategoryId = 2,
                            Description = "Description for Product 2-7",
                            MetaDescription = "Meta Description for Product 2-7",
                            MetaKeywords = "keyword-2-7",
                            MetaTitle = "Meta Title for Product 2-7",
                            Name = "Product 2-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-2-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Brand 8",
                            CategoryId = 2,
                            Description = "Description for Product 2-8",
                            MetaDescription = "Meta Description for Product 2-8",
                            MetaKeywords = "keyword-2-8",
                            MetaTitle = "Meta Title for Product 2-8",
                            Name = "Product 2-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-2-8",
                            Status = true,
                            Stock = 108
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Brand 1",
                            CategoryId = 3,
                            Description = "Description for Product 3-1",
                            MetaDescription = "Meta Description for Product 3-1",
                            MetaKeywords = "keyword-3-1",
                            MetaTitle = "Meta Title for Product 3-1",
                            Name = "Product 3-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-3-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Brand 2",
                            CategoryId = 3,
                            Description = "Description for Product 3-2",
                            MetaDescription = "Meta Description for Product 3-2",
                            MetaKeywords = "keyword-3-2",
                            MetaTitle = "Meta Title for Product 3-2",
                            Name = "Product 3-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-3-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Brand 3",
                            CategoryId = 3,
                            Description = "Description for Product 3-3",
                            MetaDescription = "Meta Description for Product 3-3",
                            MetaKeywords = "keyword-3-3",
                            MetaTitle = "Meta Title for Product 3-3",
                            Name = "Product 3-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-3-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Brand 4",
                            CategoryId = 3,
                            Description = "Description for Product 3-4",
                            MetaDescription = "Meta Description for Product 3-4",
                            MetaKeywords = "keyword-3-4",
                            MetaTitle = "Meta Title for Product 3-4",
                            Name = "Product 3-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-3-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Brand 5",
                            CategoryId = 3,
                            Description = "Description for Product 3-5",
                            MetaDescription = "Meta Description for Product 3-5",
                            MetaKeywords = "keyword-3-5",
                            MetaTitle = "Meta Title for Product 3-5",
                            Name = "Product 3-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-3-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Brand 6",
                            CategoryId = 3,
                            Description = "Description for Product 3-6",
                            MetaDescription = "Meta Description for Product 3-6",
                            MetaKeywords = "keyword-3-6",
                            MetaTitle = "Meta Title for Product 3-6",
                            Name = "Product 3-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-3-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Brand 7",
                            CategoryId = 3,
                            Description = "Description for Product 3-7",
                            MetaDescription = "Meta Description for Product 3-7",
                            MetaKeywords = "keyword-3-7",
                            MetaTitle = "Meta Title for Product 3-7",
                            Name = "Product 3-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-3-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Brand 8",
                            CategoryId = 3,
                            Description = "Description for Product 3-8",
                            MetaDescription = "Meta Description for Product 3-8",
                            MetaKeywords = "keyword-3-8",
                            MetaTitle = "Meta Title for Product 3-8",
                            Name = "Product 3-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-3-8",
                            Status = true,
                            Stock = 108
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Brand 1",
                            CategoryId = 4,
                            Description = "Description for Product 4-1",
                            MetaDescription = "Meta Description for Product 4-1",
                            MetaKeywords = "keyword-4-1",
                            MetaTitle = "Meta Title for Product 4-1",
                            Name = "Product 4-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-4-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Brand 2",
                            CategoryId = 4,
                            Description = "Description for Product 4-2",
                            MetaDescription = "Meta Description for Product 4-2",
                            MetaKeywords = "keyword-4-2",
                            MetaTitle = "Meta Title for Product 4-2",
                            Name = "Product 4-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-4-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Brand 3",
                            CategoryId = 4,
                            Description = "Description for Product 4-3",
                            MetaDescription = "Meta Description for Product 4-3",
                            MetaKeywords = "keyword-4-3",
                            MetaTitle = "Meta Title for Product 4-3",
                            Name = "Product 4-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-4-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Brand 4",
                            CategoryId = 4,
                            Description = "Description for Product 4-4",
                            MetaDescription = "Meta Description for Product 4-4",
                            MetaKeywords = "keyword-4-4",
                            MetaTitle = "Meta Title for Product 4-4",
                            Name = "Product 4-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-4-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Brand 5",
                            CategoryId = 4,
                            Description = "Description for Product 4-5",
                            MetaDescription = "Meta Description for Product 4-5",
                            MetaKeywords = "keyword-4-5",
                            MetaTitle = "Meta Title for Product 4-5",
                            Name = "Product 4-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-4-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Brand 6",
                            CategoryId = 4,
                            Description = "Description for Product 4-6",
                            MetaDescription = "Meta Description for Product 4-6",
                            MetaKeywords = "keyword-4-6",
                            MetaTitle = "Meta Title for Product 4-6",
                            Name = "Product 4-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-4-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Brand 7",
                            CategoryId = 4,
                            Description = "Description for Product 4-7",
                            MetaDescription = "Meta Description for Product 4-7",
                            MetaKeywords = "keyword-4-7",
                            MetaTitle = "Meta Title for Product 4-7",
                            Name = "Product 4-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-4-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Brand 8",
                            CategoryId = 4,
                            Description = "Description for Product 4-8",
                            MetaDescription = "Meta Description for Product 4-8",
                            MetaKeywords = "keyword-4-8",
                            MetaTitle = "Meta Title for Product 4-8",
                            Name = "Product 4-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-4-8",
                            Status = true,
                            Stock = 108
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Brand 1",
                            CategoryId = 5,
                            Description = "Description for Product 5-1",
                            MetaDescription = "Meta Description for Product 5-1",
                            MetaKeywords = "keyword-5-1",
                            MetaTitle = "Meta Title for Product 5-1",
                            Name = "Product 5-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-5-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Brand 2",
                            CategoryId = 5,
                            Description = "Description for Product 5-2",
                            MetaDescription = "Meta Description for Product 5-2",
                            MetaKeywords = "keyword-5-2",
                            MetaTitle = "Meta Title for Product 5-2",
                            Name = "Product 5-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-5-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Brand 3",
                            CategoryId = 5,
                            Description = "Description for Product 5-3",
                            MetaDescription = "Meta Description for Product 5-3",
                            MetaKeywords = "keyword-5-3",
                            MetaTitle = "Meta Title for Product 5-3",
                            Name = "Product 5-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-5-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Brand 4",
                            CategoryId = 5,
                            Description = "Description for Product 5-4",
                            MetaDescription = "Meta Description for Product 5-4",
                            MetaKeywords = "keyword-5-4",
                            MetaTitle = "Meta Title for Product 5-4",
                            Name = "Product 5-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-5-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Brand 5",
                            CategoryId = 5,
                            Description = "Description for Product 5-5",
                            MetaDescription = "Meta Description for Product 5-5",
                            MetaKeywords = "keyword-5-5",
                            MetaTitle = "Meta Title for Product 5-5",
                            Name = "Product 5-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-5-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Brand 6",
                            CategoryId = 5,
                            Description = "Description for Product 5-6",
                            MetaDescription = "Meta Description for Product 5-6",
                            MetaKeywords = "keyword-5-6",
                            MetaTitle = "Meta Title for Product 5-6",
                            Name = "Product 5-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-5-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Brand 7",
                            CategoryId = 5,
                            Description = "Description for Product 5-7",
                            MetaDescription = "Meta Description for Product 5-7",
                            MetaKeywords = "keyword-5-7",
                            MetaTitle = "Meta Title for Product 5-7",
                            Name = "Product 5-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-5-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Brand 8",
                            CategoryId = 5,
                            Description = "Description for Product 5-8",
                            MetaDescription = "Meta Description for Product 5-8",
                            MetaKeywords = "keyword-5-8",
                            MetaTitle = "Meta Title for Product 5-8",
                            Name = "Product 5-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-5-8",
                            Status = true,
                            Stock = 108
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Brand 1",
                            CategoryId = 6,
                            Description = "Description for Product 6-1",
                            MetaDescription = "Meta Description for Product 6-1",
                            MetaKeywords = "keyword-6-1",
                            MetaTitle = "Meta Title for Product 6-1",
                            Name = "Product 6-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-6-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Brand 2",
                            CategoryId = 6,
                            Description = "Description for Product 6-2",
                            MetaDescription = "Meta Description for Product 6-2",
                            MetaKeywords = "keyword-6-2",
                            MetaTitle = "Meta Title for Product 6-2",
                            Name = "Product 6-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-6-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Brand 3",
                            CategoryId = 6,
                            Description = "Description for Product 6-3",
                            MetaDescription = "Meta Description for Product 6-3",
                            MetaKeywords = "keyword-6-3",
                            MetaTitle = "Meta Title for Product 6-3",
                            Name = "Product 6-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-6-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Brand 4",
                            CategoryId = 6,
                            Description = "Description for Product 6-4",
                            MetaDescription = "Meta Description for Product 6-4",
                            MetaKeywords = "keyword-6-4",
                            MetaTitle = "Meta Title for Product 6-4",
                            Name = "Product 6-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-6-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Brand 5",
                            CategoryId = 6,
                            Description = "Description for Product 6-5",
                            MetaDescription = "Meta Description for Product 6-5",
                            MetaKeywords = "keyword-6-5",
                            MetaTitle = "Meta Title for Product 6-5",
                            Name = "Product 6-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-6-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Brand 6",
                            CategoryId = 6,
                            Description = "Description for Product 6-6",
                            MetaDescription = "Meta Description for Product 6-6",
                            MetaKeywords = "keyword-6-6",
                            MetaTitle = "Meta Title for Product 6-6",
                            Name = "Product 6-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-6-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Brand 7",
                            CategoryId = 6,
                            Description = "Description for Product 6-7",
                            MetaDescription = "Meta Description for Product 6-7",
                            MetaKeywords = "keyword-6-7",
                            MetaTitle = "Meta Title for Product 6-7",
                            Name = "Product 6-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-6-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Brand 8",
                            CategoryId = 6,
                            Description = "Description for Product 6-8",
                            MetaDescription = "Meta Description for Product 6-8",
                            MetaKeywords = "keyword-6-8",
                            MetaTitle = "Meta Title for Product 6-8",
                            Name = "Product 6-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-6-8",
                            Status = true,
                            Stock = 108
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Brand 1",
                            CategoryId = 7,
                            Description = "Description for Product 7-1",
                            MetaDescription = "Meta Description for Product 7-1",
                            MetaKeywords = "keyword-7-1",
                            MetaTitle = "Meta Title for Product 7-1",
                            Name = "Product 7-1",
                            Price = 11.99m,
                            Rating = 2,
                            Slug = "product-7-1",
                            Status = true,
                            Stock = 101
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Brand 2",
                            CategoryId = 7,
                            Description = "Description for Product 7-2",
                            MetaDescription = "Meta Description for Product 7-2",
                            MetaKeywords = "keyword-7-2",
                            MetaTitle = "Meta Title for Product 7-2",
                            Name = "Product 7-2",
                            Price = 12.99m,
                            Rating = 3,
                            Slug = "product-7-2",
                            Status = true,
                            Stock = 102
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Brand 3",
                            CategoryId = 7,
                            Description = "Description for Product 7-3",
                            MetaDescription = "Meta Description for Product 7-3",
                            MetaKeywords = "keyword-7-3",
                            MetaTitle = "Meta Title for Product 7-3",
                            Name = "Product 7-3",
                            Price = 13.99m,
                            Rating = 4,
                            Slug = "product-7-3",
                            Status = true,
                            Stock = 103
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Brand 4",
                            CategoryId = 7,
                            Description = "Description for Product 7-4",
                            MetaDescription = "Meta Description for Product 7-4",
                            MetaKeywords = "keyword-7-4",
                            MetaTitle = "Meta Title for Product 7-4",
                            Name = "Product 7-4",
                            Price = 14.99m,
                            Rating = 5,
                            Slug = "product-7-4",
                            Status = true,
                            Stock = 104
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Brand 5",
                            CategoryId = 7,
                            Description = "Description for Product 7-5",
                            MetaDescription = "Meta Description for Product 7-5",
                            MetaKeywords = "keyword-7-5",
                            MetaTitle = "Meta Title for Product 7-5",
                            Name = "Product 7-5",
                            Price = 15.99m,
                            Rating = 1,
                            Slug = "product-7-5",
                            Status = true,
                            Stock = 105
                        },
                        new
                        {
                            Id = 54,
                            Brand = "Brand 6",
                            CategoryId = 7,
                            Description = "Description for Product 7-6",
                            MetaDescription = "Meta Description for Product 7-6",
                            MetaKeywords = "keyword-7-6",
                            MetaTitle = "Meta Title for Product 7-6",
                            Name = "Product 7-6",
                            Price = 16.99m,
                            Rating = 2,
                            Slug = "product-7-6",
                            Status = true,
                            Stock = 106
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Brand 7",
                            CategoryId = 7,
                            Description = "Description for Product 7-7",
                            MetaDescription = "Meta Description for Product 7-7",
                            MetaKeywords = "keyword-7-7",
                            MetaTitle = "Meta Title for Product 7-7",
                            Name = "Product 7-7",
                            Price = 17.99m,
                            Rating = 3,
                            Slug = "product-7-7",
                            Status = true,
                            Stock = 107
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Brand 8",
                            CategoryId = 7,
                            Description = "Description for Product 7-8",
                            MetaDescription = "Meta Description for Product 7-8",
                            MetaKeywords = "keyword-7-8",
                            MetaTitle = "Meta Title for Product 7-8",
                            Name = "Product 7-8",
                            Price = 18.99m,
                            Rating = 4,
                            Slug = "product-7-8",
                            Status = true,
                            Stock = 108
                        });
                });

            modelBuilder.Entity("TestApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestApp.Models.Image", b =>
                {
                    b.HasOne("TestApp.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TestApp.Models.Product", b =>
                {
                    b.HasOne("TestApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TestApp.Models.Review", b =>
                {
                    b.HasOne("TestApp.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TestApp.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
